### ISSUE TITLE
Set up basic app page and structure

### ISSUE THREAD

**Issue by danrademacher** [OpenHistoricalMap/ohm-inspector#1]
Based on the pattern in this example:
https://greeninfo-network.github.io/cnra-gazetteer/

Let's set up basic sample app and underlying structure. 

Inputs:
* API version -- this is `0.6` globally but could change in future so let's make a place to define
* geom type -- one of `nod`, `,way`, `relation`
* OSM ID -- an integer

Let's also add links to make it easy to load these two examples:
* http://www.openhistoricalmap.org/api/0.6/way/198099635
* http://www.openhistoricalmap.org/api/0.6/way/198287637

We probably want the configuration of the app itself to include setting the AIP root URL, in our case `http://www.openhistoricalmap.org/api/`

Maybe first pass here is that we can set these variables and get the output of the XML on the page?

**Comment by gregallensworth** [comment]
The basic build system and demo page concept are in place. Upon cloning and running `nvm use` and `npm start` per the docs, one may visit localhost to get a demo page. This demo page is a form using GET method to itself, therefore supports URL params to pre-load a given way/node/relation 

Examples:
http://localhost:8749/
http://localhost:8749/?osmtype=way&osmid=198293468
http://localhost:8749/?osmtype=way&osmid=198180481
http://localhost:8749/?osmtype=way&osmid=198099635
http://localhost:8749/?osmtype=way&osmid=198287637

This is merely placeholder functionality, for how the site would eventually have routing to a URL, e.g. `/way/198287637` would fill in some JavaScript parameters, or take some other server-side behavior... We need to find out how they want to detect params and instantiate the widget, so we can code for that.

**Comment by danrademacher** [comment]
Note: I updated links in previous comment to work in GH Pages

**Comment by gregallensworth** [comment]
This work has been done, and continued in #2 where the content has been fleshed out more fully.
