### ISSUE TITLE
Visual design pass on basic sidebar content display

### ISSUE THREAD

**Issue by danrademacher** [OpenHistoricalMap/ohm-inspector#19]
To work with this in approximation of final environment, see this handy script paste-infrom gregor:
https://github.com/OpenHistoricalMap/ohm-inspector/issues/18#issuecomment-541171282

I think visual design here is going to be light touch as expected. A few highlights:

1. Chevrons on images, something a bit more refined:
![image](https://user-images.githubusercontent.com/1423200/67698309-5be20e80-f967-11e9-84bc-bd033891cece.png)
2. Visual indicator that Lightbox is an option (click image to see it happen)
3. Update lightbox treatment, with some transparency on scrim nicer close X. Currently looks like 
![image](https://user-images.githubusercontent.com/1423200/67698389-846a0880-f967-11e9-9762-b3b89c7c91d0.png)

Maybe just borrow heavily from Google Material Design buttons for these that we've been using elsewhere recently?

Project code at Greeninfo is `Open Historical Map:Inspector`

**Comment by gregallensworth** [comment]
I redid the lightbox behavior to be much nicer than my original, grey version. This borrows from the intent we had with Fluidbox, to expand outward from the slide's position so as t keep a sense of continuity from that position.

![inspector-lightbox-animation-1](https://user-images.githubusercontent.com/3117633/67883849-0857f800-fb02-11e9-9aca-be80b249e76a.gif)
