### ISSUE TITLE
Remove OSM ID from new inspector header?

### ISSUE THREAD

**Issue by danrademacher** [OpenHistoricalMap/ohm-inspector#20]
During review last week, Jeff asked about removing the Way ID here: 
![image](https://user-images.githubusercontent.com/1423200/67698587-dca10a80-f967-11e9-8da3-ab05ba7ca48a.png)

With an eye toward making this as non-OSM-technical as possible. 

Would apply to Nodes and Relations too.

**Comment by danrademacher** [comment]
To clarify this, when we are showing the new view, we would see:
![image](https://user-images.githubusercontent.com/1423200/67699993-576b2500-f96a-11e9-9d7e-935ad80ccdd1.png)

And when user switches to classic inspector, they see:
![image](https://user-images.githubusercontent.com/1423200/67700065-7d90c500-f96a-11e9-8172-7e74c581e795.png)

**Comment by gregallensworth** [comment]
This is now in place, e.g. https://openhistoricalmap.github.io/ohm-inspector/?osmtype=way&osmid=198099635

The panel now inserts its own H2 inside the panel for use as a titlebar. Toggling classic/ohm view shows/hides the original H2 titlebar.

**OHM INSPECTOR: now has its own titlebar of just the feature name**

![image](https://user-images.githubusercontent.com/3117633/67701745-c007d100-f96d-11e9-940f-dae4738ccfc7.png)

**CLASSIC: the built-in title bar with Type Name (ID)**

![image](https://user-images.githubusercontent.com/3117633/67701755-c8600c00-f96d-11e9-884e-29705dd62779.png)

**Comment by gregallensworth** [comment]
Another visual demonstration, using injected mode to test.

![image](https://user-images.githubusercontent.com/3117633/67701920-0fe69800-f96e-11e9-82ae-099b73c26dff.png)

![image](https://user-images.githubusercontent.com/3117633/67702013-399fbf00-f96e-11e9-8ded-6b2b1e48cb9c.png)
